stages:
  - build
  - deploy

build:
  stage: build
  script:
    - apt-get update
    - apt-get install dh-systemd
    - ./make_debian_changelog.sh
    - dpkg-buildpackage -us -uc
    - mkdir build
    - mv ../olinuxino-tools*.deb build/
  tags:
    - build
  artifacts:
    paths:
      - build/*

deploy:staging:
  stage: deploy
  script:
    - |
      for repo in $REPOS ; do
        reprepro -b /var/www/html/staging/ --ignore=wrongdistribution includedeb $repo build/olinuxino-tools*.deb
      done
  tags:
    - deploy

deploy:repository:
  only:
    - master
  stage: deploy
  script:
    - |
      for repo in $REPOS ; do
        reprepro -b /var/www/html/repository/ --ignore=wrongdistribution includedeb $repo build/olinuxino-tools*.deb
      done
  tags:
    - deploy
