#!/bin/bash

ROOT_DIR=$(dirname $(realpath "$0"))
source ${ROOT_DIR}/library.sh

# enable default overlays
enable_overlays

# update mime database
if [ -f /usr/share/mime/aliases -a ! -s /usr/share/mime/aliases ] ; then
  update-mime-database /usr/share/mime &>/dev/null || :
fi

systemctl disable olinuxino-firstboot.service
